"""empty message

Revision ID: 767c69cde9cc
Revises: 28a9b26cc4b5
Create Date: 2022-12-30 00:44:30.402137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767c69cde9cc'
down_revision = '28a9b26cc4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.add_column('vehicle', sa.Column('cost_in_credits', sa.String(length=50), nullable=True))
    op.drop_column('vehicle', 'population')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('vehicle', 'cost_in_credits')
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    # ### end Alembic commands ###
